//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestingTest {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class UnitTesting : global::System.Configuration.ApplicationSettingsBase {
        
        private static UnitTesting defaultInstance = ((UnitTesting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UnitTesting())));
        
        public static UnitTesting Default {
            get {
                return defaultInstance;
            }
        }
    }
}
